### ISSUE TITLE
Answer / Note Clarification

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-combinations#2]
Suggest clarifying the answer and the final note on this sentence:

"Note how 6 in our coverband example  =6=3!=6=3! , as expected." 

This note is confusing since the total combination should be 56.

#combinations, order not matter
import math

n = 8
k = 3

#combinations, order not matter
comb = math.factorial(n) / (math.factorial(n-k)*math.factorial(3))
print(comb)

**Comment by LoreDirick** [comment]
Hi @benjamin-jacobson: 
Agreed that the way it was written was confusing, especially as the real answer (56) was nowhere to be found. Fixed it now! Thank you.
